// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dslmkqjlmwvypzvhvkfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzbG1rcWpsbXd2eXB6dmh2a2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NjcyNDcsImV4cCI6MjA2MDU0MzI0N30._Wv1ziOijidFGanc2TztQOHC3wAwpk6rQO1e1yzhLvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);